import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.50.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { userId, timeframe, progressData } = await req.json();
    
    const openAIApiKey = Deno.env.get('OPENAI_API_KEY');
    if (!openAIApiKey) {
      throw new Error('OPENAI_API_KEY is not configured');
    }

    // Create Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Generate AI analysis of progress data
    const systemPrompt = `You are a career development analyst. Create a comprehensive progress report analyzing the user's career development journey.`;

    const userPrompt = `Analyze this career progress data for ${timeframe}:

    ${JSON.stringify(progressData, null, 2)}

    Generate a professional progress report with:
    - Executive summary of progress
    - Key achievements and milestones
    - Areas of growth and improvement
    - Trends and patterns analysis
    - Recommendations for future development
    - Goals for the next period

    Format as HTML that can be converted to PDF with professional styling.`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.7,
        max_tokens: 2000,
      }),
    });

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.status}`);
    }

    const data = await response.json();
    const htmlContent = data.choices[0].message.content;

    // Create a complete HTML document with styling
    const fullHtml = `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Career Progress Report</title>
        <style>
            body { 
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
                line-height: 1.6; 
                margin: 40px; 
                color: #333; 
            }
            h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
            h2 { color: #34495e; margin-top: 30px; }
            .header { text-align: center; margin-bottom: 40px; }
            .summary { background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }
            .achievement { background: #e8f5e8; padding: 15px; margin: 10px 0; border-radius: 5px; }
            .recommendation { background: #fff3cd; padding: 15px; margin: 10px 0; border-radius: 5px; }
            .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Career Progress Report</h1>
            <p><strong>Period:</strong> ${timeframe}</p>
            <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
        </div>
        ${htmlContent}
        <div class="footer">
            <p>Generated by EmpowerCareer - Your Career Development Platform</p>
        </div>
    </body>
    </html>`;

    console.log(`Generated progress PDF for user ${userId}, timeframe: ${timeframe}`);

    // Return the HTML content that can be converted to PDF on the client side
    return new Response(JSON.stringify({ 
      htmlContent: fullHtml,
      filename: `career-progress-${timeframe}-${new Date().toISOString().split('T')[0]}.pdf`
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Error in export-progress-pdf:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});