
-- Insert Watson-Glaser Critical Thinking Appraisal test
INSERT INTO test_types (
    id,
    name,
    description,
    category_id,
    questions_count,
    estimated_duration,
    subscription_required
) VALUES (
    'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f',
    'Watson-Glaser Critical Thinking Appraisal',
    'Evaluează capacitățile de gândire critică prin 5 dimensiuni: inferențe, asumpții, deducție, interpretare și evaluarea argumentelor.',
    '13f9d37c-2a3b-4e55-8707-e0372b3b2581',
    40,
    25,
    'basic'
);

-- Insert Watson-Glaser questions
-- Inference questions (1-8)
INSERT INTO test_questions (id, test_type_id, question_order, question_text_ro, question_text_en, question_type, options, options_en) VALUES
('wg-q001', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 1, 'Un grup de economisti a raportat că un salariat cu normă întreagă câștigă în medie cu 40% mai mult decât un salariat cu jumătate de normă. Din această informație putem concluziona:', 'A group of economists reported that a full-time employee earns on average 40% more than a part-time employee. From this information we can conclude:', 'multiple_choice', '["Foarte probabil", "Probabil", "Insuficient de probabil", "Foarte puțin probabil"]', '["Very likely", "Likely", "Insufficiently probable", "Very unlikely"]'),
('wg-q002', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 2, 'Studiile arată că persoanele care citesc regulat au un vocabular mai bogat. Maria citește zilnic. Prin urmare:', 'Studies show that people who read regularly have a richer vocabulary. Maria reads daily. Therefore:', 'multiple_choice', '["Foarte probabil", "Probabil", "Insuficient de probabil", "Foarte puțin probabil"]', '["Very likely", "Likely", "Insufficiently probable", "Very unlikely"]'),
('wg-q003', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 3, 'În ultimii 5 ani, vânzările de biciclete electrice au crescut cu 200%. Prin urmare, popularitatea acestora va continua să crească:', 'In the last 5 years, electric bike sales have increased by 200%. Therefore, their popularity will continue to grow:', 'multiple_choice', '["Foarte probabil", "Probabil", "Insuficient de probabil", "Foarte puțin probabil"]', '["Very likely", "Likely", "Insufficiently probable", "Very unlikely"]'),
('wg-q004', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 4, 'Raportul arată că 80% dintre studenți preferă învățarea online. Pe baza acestei informații, putem spune că învățarea tradițională va dispărea:', 'The report shows that 80% of students prefer online learning. Based on this information, we can say that traditional learning will disappear:', 'multiple_choice', '["Foarte probabil", "Probabil", "Insuficient de probabil", "Foarte puțin probabil"]', '["Very likely", "Likely", "Insufficiently probable", "Very unlikely"]'),
('wg-q005', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 5, 'Compania X a investit masiv în tehnologie și productivitatea a crescut cu 30%. Alte companii care vor investi similar vor avea aceleași rezultate:', 'Company X invested heavily in technology and productivity increased by 30%. Other companies that invest similarly will have the same results:', 'multiple_choice', '["Foarte probabil", "Probabil", "Insuficient de probabil", "Foarte puțin probabil"]', '["Very likely", "Likely", "Insufficiently probable", "Very unlikely"]'),
('wg-q006', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 6, 'Studiul indică că oamenii care fac exerciții regulate dorm mai bine. Andrei face sport zilnic, prin urmare doarme mai bine decât cei care nu fac sport:', 'The study indicates that people who exercise regularly sleep better. Andrei exercises daily, therefore he sleeps better than those who do not exercise:', 'multiple_choice', '["Foarte probabil", "Probabil", "Insuficient de probabil", "Foarte puțin probabil"]', '["Very likely", "Likely", "Insufficiently probable", "Very unlikely"]'),
('wg-q007', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 7, 'Datele arată că în orașele cu transport public eficient, poluarea aerului este mai mică. Prin urmare, toate orașele ar trebui să investească în transport public pentru a reduce poluarea:', 'Data shows that in cities with efficient public transport, air pollution is lower. Therefore, all cities should invest in public transport to reduce pollution:', 'multiple_choice', '["Foarte probabil", "Probabil", "Insuficient de probabil", "Foarte puțin probabil"]', '["Very likely", "Likely", "Insufficiently probable", "Very unlikely"]'),
('wg-q008', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 8, 'Cercetarea arată că angajații care lucrează de acasă raportează o satisfacție mai mare. Pe baza acestei informații, toate companiile ar trebui să adopte munca de acasă:', 'Research shows that employees who work from home report higher satisfaction. Based on this information, all companies should adopt working from home:', 'multiple_choice', '["Foarte probabil", "Probabil", "Insuficient de probabil", "Foarte puțin probabil"]', '["Very likely", "Likely", "Insufficiently probable", "Very unlikely"]');

-- Assumptions questions (9-16)
INSERT INTO test_questions (id, test_type_id, question_order, question_text_ro, question_text_en, question_type, options, options_en) VALUES
('wg-q009', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 9, 'Afirmația: "Companiile care investesc în formarea angajaților au o productivitate mai mare." Această afirmație presupune că:', 'Statement: "Companies that invest in employee training have higher productivity." This statement assumes that:', 'binary_choice', '["Asumpție făcută", "Asumpție nu este făcută"]', '["Assumption made", "Assumption not made"]'),
('wg-q010', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 10, 'Argumentul: "Trebuie să creștem bugetul pentru educație pentru a améliora performanțele școlare." Se presupune că:', 'Argument: "We need to increase the education budget to improve school performance." It is assumed that:', 'binary_choice', '["Asumpție făcută", "Asumpție nu este făcută"]', '["Assumption made", "Assumption not made"]'),
('wg-q011', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 11, 'Declarația: "Medicii recomandă exerciții fizice pentru o viață sănătoasă." Se presupune că exercițiile fizice sunt benefice pentru sănătate:', 'Statement: "Doctors recommend physical exercise for a healthy life." It is assumed that physical exercise is beneficial for health:', 'binary_choice', '["Asumpție făcută", "Asumpție nu este făcută"]', '["Assumption made", "Assumption not made"]'),
('wg-q012', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 12, 'Afirmația: "Pentru a reduce criminalitatea, trebuie să angajăm mai mulți polițiști." Se presupune că mai mulți polițiști duc la reducerea criminalității:', 'Statement: "To reduce crime, we need to hire more police officers." It is assumed that more police officers lead to reduced crime:', 'binary_choice', '["Asumpție făcută", "Asumpție nu este făcută"]', '["Assumption made", "Assumption not made"]'),
('wg-q013', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 13, 'Argumentul: "Compania noastră trebuie să investească în tehnologii noi pentru a rămâne competitivă." Se presupune că tehnologiile noi oferă avantaje competitive:', 'Argument: "Our company needs to invest in new technologies to remain competitive." It is assumed that new technologies provide competitive advantages:', 'binary_choice', '["Asumpție făcută", "Asumpție nu este făcută"]', '["Assumption made", "Assumption not made"]'),
('wg-q014', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 14, 'Declarația: "Părinții ar trebui să limiteze timpul petrecut de copii în fața ecranelor pentru a proteja vederea." Se presupune că ecranele afectează vederea:', 'Statement: "Parents should limit children screen time to protect their vision." It is assumed that screens affect vision:', 'binary_choice', '["Asumpție făcută", "Asumpție nu este făcută"]', '["Assumption made", "Assumption not made"]'),
('wg-q015', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 15, 'Afirmația: "Guvernul ar trebui să crească taxele pentru a finanța serviciile publice." Se presupune că taxele mai mari îmbunătățesc serviciile publice:', 'Statement: "The government should raise taxes to fund public services." It is assumed that higher taxes improve public services:', 'binary_choice', '["Asumpție făcută", "Asumpție nu este făcută"]', '["Assumption made", "Assumption not made"]'),
('wg-q016', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 16, 'Argumentul: "Ar trebui să reducem emisiile de carbon pentru a combate schimbările climatice." Se presupune că emisiile de carbon contribuie la schimbările climatice:', 'Argument: "We should reduce carbon emissions to combat climate change." It is assumed that carbon emissions contribute to climate change:', 'binary_choice', '["Asumpție făcută", "Asumpție nu este făcută"]', '["Assumption made", "Assumption not made"]');

-- Deduction questions (17-24)
INSERT INTO test_questions (id, test_type_id, question_order, question_text_ro, question_text_en, question_type, options, options_en) VALUES
('wg-q017', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 17, 'Premisa: "Toți angajații cu performanțe excelente primesc bonusuri. Maria are performanțe excelente." Concluzia: "Maria primește bonus."', 'Premise: "All employees with excellent performance receive bonuses. Maria has excellent performance." Conclusion: "Maria receives a bonus."', 'binary_choice', '["Concluzia urmează", "Concluzia nu urmează"]', '["Conclusion follows", "Conclusion does not follow"]'),
('wg-q018', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 18, 'Premisa: "Unele mașini sunt electrice. Toate mașinile electrice sunt ecologice." Concluzia: "Toate mașinile sunt ecologice."', 'Premise: "Some cars are electric. All electric cars are eco-friendly." Conclusion: "All cars are eco-friendly."', 'binary_choice', '["Concluzia urmează", "Concluzia nu urmează"]', '["Conclusion follows", "Conclusion does not follow"]'),
('wg-q019', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 19, 'Premisa: "Toți studenții care studiază zilnic trec examenele. Ana studiază zilnic." Concluzia: "Ana trece examenele."', 'Premise: "All students who study daily pass exams. Ana studies daily." Conclusion: "Ana passes exams."', 'binary_choice', '["Concluzia urmează", "Concluzia nu urmează"]', '["Conclusion follows", "Conclusion does not follow"]'),
('wg-q020', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 20, 'Premisa: "Toți managerii au experiență în leadership. Paul este manager." Concluzia: "Paul are experiență în leadership."', 'Premise: "All managers have leadership experience. Paul is a manager." Conclusion: "Paul has leadership experience."', 'binary_choice', '["Concluzia urmează", "Concluzia nu urmează"]', '["Conclusion follows", "Conclusion does not follow"]'),
('wg-q021', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 21, 'Premisa: "Toți doctorii au studii superioare. Elena este doctor." Concluzia: "Elena are studii superioare."', 'Premise: "All doctors have higher education. Elena is a doctor." Conclusion: "Elena has higher education."', 'binary_choice', '["Concluzia urmează", "Concluzia nu urmează"]', '["Conclusion follows", "Conclusion does not follow"]'),
('wg-q022', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 22, 'Premisa: "Toți programatorii cunosc matematica. Radu este programator." Concluzia: "Radu cunoaște matematica."', 'Premise: "All programmers know mathematics. Radu is a programmer." Conclusion: "Radu knows mathematics."', 'binary_choice', '["Concluzia urmează", "Concluzia nu urmează"]', '["Conclusion follows", "Conclusion does not follow"]'),
('wg-q023', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 23, 'Premisa: "Toate plantele au nevoie de apă pentru a supraviețui. Trandafirii sunt plante." Concluzia: "Trandafirii au nevoie de apă pentru a supraviețui."', 'Premise: "All plants need water to survive. Roses are plants." Conclusion: "Roses need water to survive."', 'binary_choice', '["Concluzia urmează", "Concluzia nu urmează"]', '["Conclusion follows", "Conclusion does not follow"]'),
('wg-q024', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 24, 'Premisa: "Toți sportivii profesioniști se antrenează zilnic. Cristian este sportiv profesionist." Concluzia: "Cristian se antrenează zilnic."', 'Premise: "All professional athletes train daily. Cristian is a professional athlete." Conclusion: "Cristian trains daily."', 'binary_choice', '["Concluzia urmează", "Concluzia nu urmează"]', '["Conclusion follows", "Conclusion does not follow"]');

-- Interpretation questions (25-32)
INSERT INTO test_questions (id, test_type_id, question_order, question_text_ro, question_text_en, question_type, options, options_en) VALUES
('wg-q025', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 25, 'Studiul arată: "75% dintre respondenți preferă produsul A." Interpretarea: "Produsul A este preferat de majoritatea consumatorilor de pe piață."', 'Study shows: "75% of respondents prefer product A." Interpretation: "Product A is preferred by the majority of consumers in the market."', 'binary_choice', '["Interpretarea urmează", "Interpretarea nu urmează"]', '["Interpretation follows", "Interpretation does not follow"]'),
('wg-q026', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 26, 'Datele indică: "Vânzările au scăzut cu 10% în ultima lună." Interpretarea: "Compania își va pierde toți clienții în curând."', 'Data indicates: "Sales have decreased by 10% in the last month." Interpretation: "The company will lose all its customers soon."', 'binary_choice', '["Interpretarea urmează", "Interpretarea nu urmează"]', '["Interpretation follows", "Interpretation does not follow"]'),
('wg-q027', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 27, 'Raportul menționează: "60% dintre angajați sunt mulțumiți de beneficii." Interpretarea: "Majoritatea angajaților sunt mulțumiți de beneficii."', 'Report mentions: "60% of employees are satisfied with benefits." Interpretation: "Most employees are satisfied with benefits."', 'binary_choice', '["Interpretarea urmează", "Interpretarea nu urmează"]', '["Interpretation follows", "Interpretation does not follow"]'),
('wg-q028', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 28, 'Cercetarea arată: "Studenții care folosesc tehnologia în clasă au rezultate cu 15% mai bune." Interpretarea: "Tehnologia îmbunătățește performanțele școlare."', 'Research shows: "Students who use technology in class have 15% better results." Interpretation: "Technology improves academic performance."', 'binary_choice', '["Interpretarea urmează", "Interpretarea nu urmează"]', '["Interpretation follows", "Interpretation does not follow"]'),
('wg-q029', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 29, 'Studiul indică: "Oamenii care mănâncă fructe zilnic au un risc cu 20% mai mic de boli cardiace." Interpretarea: "Fructele previn în totalitate bolile cardiace."', 'Study indicates: "People who eat fruit daily have a 20% lower risk of heart disease." Interpretation: "Fruits completely prevent heart disease."', 'binary_choice', '["Interpretarea urmează", "Interpretarea nu urmează"]', '["Interpretation follows", "Interpretation does not follow"]'),
('wg-q030', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 30, 'Analiza arată: "Companiile cu programe de diversitate au o rată de retenție cu 25% mai mare." Interpretarea: "Diversitatea îmbunătățește retenția angajaților."', 'Analysis shows: "Companies with diversity programs have a 25% higher retention rate." Interpretation: "Diversity improves employee retention."', 'binary_choice', '["Interpretarea urmează", "Interpretarea nu urmează"]', '["Interpretation follows", "Interpretation does not follow"]'),
('wg-q031', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 31, 'Datele arată: "Orașele cu mai multe spații verzi au locuitori cu un nivel de stres mai scăzut." Interpretarea: "Spațiile verzi reduc stresul urban."', 'Data shows: "Cities with more green spaces have residents with lower stress levels." Interpretation: "Green spaces reduce urban stress."', 'binary_choice', '["Interpretarea urmează", "Interpretarea nu urmează"]', '["Interpretation follows", "Interpretation does not follow"]'),
('wg-q032', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 32, 'Studiul arată: "Companiile care oferă flexibilitate în program au angajați cu productivitate cu 30% mai mare." Interpretarea: "Flexibilitatea este singurul factor care influențează productivitatea."', 'Study shows: "Companies that offer schedule flexibility have employees with 30% higher productivity." Interpretation: "Flexibility is the only factor that influences productivity."', 'binary_choice', '["Interpretarea urmează", "Interpretarea nu urmează"]', '["Interpretation follows", "Interpretation does not follow"]');

-- Argument Evaluation questions (33-40)
INSERT INTO test_questions (id, test_type_id, question_order, question_text_ro, question_text_en, question_type, options, options_en) VALUES
('wg-q033', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 33, 'Întrebare: "Ar trebui să investim în energie regenerabilă?" Argument: "Energia regenerabilă reduce dependența de combustibilii fosili și protejează mediul."', 'Question: "Should we invest in renewable energy?" Argument: "Renewable energy reduces dependence on fossil fuels and protects the environment."', 'binary_choice', '["Argument puternic", "Argument slab"]', '["Strong argument", "Weak argument"]'),
('wg-q034', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 34, 'Întrebare: "Ar trebui să interzici folosirea telefoanelor în școli?" Argument: "Telefonul meu este nou și îmi place să îl folosesc."', 'Question: "Should we ban phone use in schools?" Argument: "My phone is new and I like using it."', 'binary_choice', '["Argument puternic", "Argument slab"]', '["Strong argument", "Weak argument"]'),
('wg-q035', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 35, 'Întrebare: "Ar trebui să creștem bugetul pentru sănătate?" Argument: "Un sistem de sănătate robust îmbunătățește calitatea vieții și reduce costurile pe termen lung."', 'Question: "Should we increase the health budget?" Argument: "A robust healthcare system improves quality of life and reduces long-term costs."', 'binary_choice', '["Argument puternic", "Argument slab"]', '["Strong argument", "Weak argument"]'),
('wg-q036', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 36, 'Întrebare: "Ar trebui să implementăm program de lucru de 4 zile?" Argument: "Îmi place să am mai mult timp liber pentru hobby-uri."', 'Question: "Should we implement a 4-day work week?" Argument: "I like having more free time for hobbies."', 'binary_choice', '["Argument puternic", "Argument slab"]', '["Strong argument", "Weak argument"]'),
('wg-q037', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 37, 'Întrebare: "Ar trebui să investim în transport public?" Argument: "Transportul public eficient reduce traficul, poluarea și oferă mobilitate tuturor cetățenilor."', 'Question: "Should we invest in public transport?" Argument: "Efficient public transport reduces traffic, pollution and provides mobility for all citizens."', 'binary_choice', '["Argument puternic", "Argument slab"]', '["Strong argument", "Weak argument"]'),
('wg-q038', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 38, 'Întrebare: "Ar trebui să reducem plastic-ul de unică folosință?" Argument: "Plastic-ul este convenabil pentru că nu trebuie să îl speli."', 'Question: "Should we reduce single-use plastic?" Argument: "Plastic is convenient because you do not have to wash it."', 'binary_choice', '["Argument puternic", "Argument slab"]', '["Strong argument", "Weak argument"]'),
('wg-q039', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 39, 'Întrebare: "Ar trebui să promovăm educația financiară în școli?" Argument: "Educația financiară dezvoltă competențe esențiale pentru managementul resurselor personale și luarea deciziilor informate."', 'Question: "Should we promote financial education in schools?" Argument: "Financial education develops essential skills for personal resource management and informed decision making."', 'binary_choice', '["Argument puternic", "Argument slab"]', '["Strong argument", "Weak argument"]'),
('wg-q040', 'e8f9a0b1-c2d3-4e5f-6789-0a1b2c3d4e5f', 40, 'Întrebare: "Ar trebui să interzici reclamele pentru junk food?" Argument: "Mie îmi plac reclamele colorate și vesele de la fast food."', 'Question: "Should we ban junk food advertising?" Argument: "I like the colorful and cheerful fast food commercials."', 'binary_choice', '["Argument puternic", "Argument slab"]', '["Strong argument", "Weak argument"]');
