
-- First, let's check if we have a personality category
INSERT INTO public.test_categories (id, name, description, icon)
VALUES (
  'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  'Teste de Personalitate',
  'Teste pentru evaluarea trăsăturilor de personalitate',
  'users'
) ON CONFLICT (id) DO NOTHING;

-- Insert the Big Five test type
INSERT INTO public.test_types (
  id,
  name,
  description,
  category_id,
  questions_count,
  estimated_duration,
  subscription_required
) VALUES (
  'f47ac10b-58cc-4372-a567-0e02b2c3d480',
  'Big Five Personality Test',
  'Evaluează cele cinci dimensiuni principale ale personalității: Extraversiune, Agreabilitate, Conștiinciozitate, Neuroticismul și Deschiderea spre experiență.',
  'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  50,
  25,
  'professional'
) ON CONFLICT (id) DO NOTHING;

-- Insert Big Five personality test questions
INSERT INTO public.test_questions (test_type_id, question_text, question_order, options, scoring_weights) VALUES
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt comunicativ și vorbesc mult.', 1, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt rezervat și îmi păstrez gândurile pentru mine.', 2, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt plin de energie și entuziasm.', 3, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Prefer să lucrez în echipă decât singur.', 4, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt timid și introspectiv.', 5, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi fac prieteni cu ușurință.', 6, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Evit să fiu centrul atenției.', 7, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi place să cunosc oameni noi.', 8, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt sociabil și îmi place să petreace timp cu alții.', 9, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi place să fiu în grupuri mari de oameni.', 10, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"extraversion": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Încerc să fiu de ajutor și să cooperez cu alții.', 11, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt sceptic și bănuitor față de intențiile altora.', 12, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt considerat și amabil cu aproape toată lumea.', 13, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Pot fi rece și detașat.', 14, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Am încredere în alții și cred în bunătatea oamenilor.', 15, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Pot fi argumentativ și certăreț.', 16, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt iertător și nu îmi păstrez resentimentele.', 17, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Tind să găsesc defecte la alții.', 18, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi place să ajut alții și să fiu generos.', 19, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi place să respect regulile și să fiu disciplinat.', 20, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"agreeableness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt o persoană conștiincioasă care își face treaba bine.', 21, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Tind să fiu dezorganizat.', 22, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt o persoană de încredere și responsabilă.', 23, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Pot fi neglijent uneori.', 24, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt perseverent până când îmi termin treaba.', 25, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Fac planuri și îi urmăresc.', 26, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt ușor distras și îmi pierd concentrarea.', 27, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt eficient și îmi termin sarcinile rapid.', 28, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi place să mențin totul organizat și îngrijit.', 29, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Amân adesea lucrurile importante.', 30, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"conscientiousness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Mă simt adesea trist și deprimat.', 31, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt relaxat și mă descurc bine cu stresul.', 32, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Mă îngrijorez mult pentru diverse lucruri.', 33, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt calm emoțional și nu mă supăr ușor.', 34, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Pot fi tensionat și nervos.', 35, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Mă schimb des la o stare de spirit la alta.', 36, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Rar mă simt trist sau deprimat.', 37, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Pot fi morocănos și mă iritez ușor.', 38, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Rămân calm în situații tensionate.', 39, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Pot deveni anxios și îngrijorat ușor.', 40, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"neuroticism": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt original și vin cu idei noi.', 41, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Prefer muncă de rutină și nu îmi place schimbarea.', 42, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt curios despre multe lucruri diferite.', 43, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt conservator și rezistent la schimbare.', 44, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Am o imaginație bogată și îmi place să visez cu ochii deschiși.', 45, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi place să experimentez și să încerc lucruri noi.', 46, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi place să reflectez și să joc cu idei.', 47, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Am puține interese artistice.', 48, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": -1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Îmi place să învăț lucruri noi și să citesc foarte mult.', 49, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": 1}'),
('f47ac10b-58cc-4372-a567-0e02b2c3d480', 'Sunt intelectual și îmi place să gândesc abstract.', 50, '[{"value": 1, "label": "Foarte neadevărat"}, {"value": 2, "label": "Moderat neadevărat"}, {"value": 3, "label": "Neutru"}, {"value": 4, "label": "Moderat adevărat"}, {"value": 5, "label": "Foarte adevărat"}]', '{"openness": 1}');
