
-- Insert HEXACO test type
INSERT INTO test_types (name, description, category_id, questions_count, estimated_duration, subscription_required)
VALUES (
  'Test HEXACO',
  'Test de personalitate HEXACO care evaluează 6 dimensiuni principale: Onestitate-Umilința, Emotivitate, Extraversiune, Agreabilitate, Conștiinciozitate și Deschidere către Experiență',
  (SELECT id FROM test_categories WHERE name = 'Personalitate' LIMIT 1),
  60,
  20,
  'basic'
);

-- Insert HEXACO questions (60 questions total, 10 per dimension)
-- Dimension 1: Honesty-Humility (Questions 1-10)
INSERT INTO test_questions (test_type_id, question_order, question_text_ro, question_text_en, options, options_en, question_type, scoring_weights) VALUES
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 1, 'Simt că merit mai mult respect decât primesc de obicei de la ceilalți.', 'I feel that I deserve more respect than the average person gets.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 2, 'Evit să profitez de cineva, chiar dacă ar fi ușor să fac asta.', 'I avoid taking advantage of someone, even when it would be easy to do so.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 3, 'Încerc să obțin ceea ce vreau, chiar dacă acest lucru îi supără pe alții.', 'I try to get what I want, even if this annoys other people.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 4, 'Cred că sunt mai important decât ceilalți.', 'I think I am more important than other people.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 5, 'Nu aș folosi niciodată flatarea pentru a obține o creștere salarială sau o promovare.', 'I would never use flattery to get a raise or promotion at work.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 6, 'Sunt atras de luxul scump.', 'I am attracted to expensive luxury goods.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 7, 'Încerc să fiu modest și umil.', 'I try to be modest and humble.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 8, 'Dacă știu că nu voi fi prins, sunt dispus să mint pentru a obține ceea ce vreau.', 'If I know that I will never get caught, I am willing to lie to get what I want.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 9, 'Încerc să nu fiu lacom sau zgârcit.', 'I try not to be greedy or materialistic.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 10, 'Cred că toate persoanele au dreptul să fie tratate cu respect și demnitate.', 'I believe that all people have the right to be treated with respect and dignity.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"honesty_humility": [2, 1, 0, -1, -2]}'),

-- Dimension 2: Emotionality (Questions 11-20)
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 11, 'Mă simt destul de anxios atunci când trebuie să vorbesc în fața unui grup mare de oameni.', 'I feel quite anxious when I have to speak in front of a large group of people.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 12, 'Mă îngrijorez mult în privința oamenilor care îmi sunt apropiați.', 'I worry a lot about the people who are close to me.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 13, 'Pot să rămân calm în situații stresante.', 'I can stay calm in stressful situations.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 14, 'Când cineva pe care îl iubesc este nefericit, mă simt și eu nefericit.', 'When someone I love is unhappy, I feel unhappy too.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 15, 'Mă sperii ușor.', 'I get scared easily.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 16, 'Îmi vine să plâng când văd pe cineva suferind.', 'I feel like crying when I see someone suffering.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 17, 'Sunt o persoană emoțională.', 'I am an emotional person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 18, 'Mă simt puternic atașat de prietenii mei apropiați.', 'I feel strongly attached to my close friends.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 19, 'Chiar și lucruri mici mă pot supăra.', 'Even small things can upset me.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 20, 'Sunt o persoană sensibilă.', 'I am a sensitive person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"emotionality": [2, 1, 0, -1, -2]}'),

-- Dimension 3: Extraversion (Questions 21-30)
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 21, 'Îmi place să fiu în centrul atenției la petreceri sociale.', 'I like to be the center of attention at social gatherings.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 22, 'Sunt o persoană liniștită.', 'I am a quiet person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 23, 'Mă simt confortabil să încep conversații cu străinii.', 'I feel comfortable starting conversations with strangers.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 24, 'Prefer să fiu singur decât să fiu cu alții.', 'I prefer to be alone rather than with other people.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 25, 'Sunt o persoană energică.', 'I am an energetic person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 26, 'Îmi place să vorbesc mult.', 'I like to talk a lot.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 27, 'Mă simt confortabil să conduc o conversație.', 'I feel comfortable leading a conversation.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 28, 'Evit să vorbesc în fața unui grup mare de oameni.', 'I avoid speaking in front of a large group of people.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 29, 'Îmi place să fiu activ și să fac multe lucruri.', 'I like to be active and do many things.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 30, 'Sunt o persoană sociabilă.', 'I am a sociable person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"extraversion": [2, 1, 0, -1, -2]}'),

-- Dimension 4: Agreeableness (Questions 31-40)
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 31, 'Mă supăr când cineva face o greșeală.', 'I get upset when someone makes a mistake.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 32, 'Sunt răbdător cu oamenii.', 'I am patient with people.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 33, 'Mă irită când oamenii nu sunt de acord cu mine.', 'I get irritated when people disagree with me.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 34, 'Încerc să evit conflictele cu ceilalți.', 'I try to avoid conflicts with others.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 35, 'Sunt o persoană îngăduitoare.', 'I am a forgiving person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 36, 'Mă supăr rapid când cineva nu respectă regulile.', 'I get angry quickly when someone doesn\'t follow the rules.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 37, 'Sunt o persoană blândă.', 'I am a gentle person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 38, 'Mă înfurii când cineva mă critică.', 'I get furious when someone criticizes me.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 39, 'Încerc să fiu cooperant în relațiile cu ceilalți.', 'I try to be cooperative in my relationships with others.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 40, 'Sunt tolerant cu oamenii care au opinii diferite.', 'I am tolerant of people who have different opinions.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"agreeableness": [2, 1, 0, -1, -2]}'),

-- Dimension 5: Conscientiousness (Questions 41-50)
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 41, 'Îmi organizez timpul cu atenție.', 'I organize my time carefully.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 42, 'Amân deseori sarcinile importante.', 'I often postpone important tasks.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 43, 'Lucrez cu atenție la detalii.', 'I work carefully with attention to details.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 44, 'Îmi pierd frecvent lucrurile.', 'I frequently lose things.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 45, 'Sunt o persoană disciplinată.', 'I am a disciplined person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 46, 'Lucrez mult pentru a-mi atinge obiectivele.', 'I work hard to achieve my goals.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 47, 'Sunt o persoană dezordonată.', 'I am a disorganized person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 48, 'Îmi respect întotdeauna promisiunile.', 'I always keep my promises.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 49, 'Mă concentrez pentru a termina sarcinile la timp.', 'I focus on completing tasks on time.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 50, 'Îmi place să fiu foarte organizat.', 'I like to be very organized.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"conscientiousness": [2, 1, 0, -1, -2]}'),

-- Dimension 6: Openness to Experience (Questions 51-60)
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 51, 'Îmi place să învăț despre istoria și politica altor țări.', 'I like to learn about the history and politics of other countries.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 52, 'Nu sunt interesat de arte abstracte.', 'I am not interested in abstract art.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 53, 'Îmi place să încerc alimente din diferite culturi.', 'I like to try foods from different cultures.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 54, 'Prefer rutina și lucrurile familiare.', 'I prefer routine and familiar things.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 55, 'Sunt o persoană creativă.', 'I am a creative person.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 56, 'Îmi place să gândesc la idei noi și neconvenționale.', 'I like to think about new and unconventional ideas.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 57, 'Nu sunt interesat de teorii filozofice.', 'I am not interested in philosophical theories.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [-2, -1, 0, 1, 2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 58, 'Apreciez frumusețea în natură și artă.', 'I appreciate beauty in nature and art.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 59, 'Îmi place să explorez idei noi și complexe.', 'I like to explore new and complex ideas.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [2, 1, 0, -1, -2]}'),
((SELECT id FROM test_types WHERE name = 'Test HEXACO'), 60, 'Sunt curios să învăț despre diferite culturi și tradiții.', 'I am curious to learn about different cultures and traditions.', '["Complet dezacord", "Dezacord", "Neutru", "Acord", "Complet acord"]', '["Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"]', 'likert_scale', '{"openness": [2, 1, 0, -1, -2]}');
